version: "3"
services:
  jenkins: 
    build: jenkins/.
    image: jenkinsdevops
    container_name: jenkinsdevops
    ports:
      - "8080:8080" 
    volumes:
      - "./jenkins/jenkins_home:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock" 
    privileged: true
    user: root
    networks:
      - net
    restart: alway
networks:
  net:
