name: Master Deploy
on:
    workflow_dispatch:
    push:
        branches:
            - master
jobs:
    deploy-staging:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        name: Deploy Obrador Master
        steps:
            - name: Pull from GitHub
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.REMOTE_HOST }}
                  username: ${{ secrets.REMOTE_USER }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: cd /home/ && git clone https://github.com/Ohernandezm/Devops-docker.git devops
cd devops