name: Master Deploy
on:
    workflow_dispatch:
    push:
        branches:
            - master
jobs:
    deploy-staging:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        name: Deploy Obrador Master
        steps:
            - name: Pull from GitHub
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.REMOTE_HOST }}
                  username: ${{ secrets.REMOTE_USER }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: cd /home/devops && rm -R Devops-docker && ${{ secrets.CLONE_CMD_SCRIPT }}
            - name: Docker Build
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.REMOTE_HOST }}
                  username: ${{ secrets.REMOTE_USER }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: |
                    cd /home/devops/Devops-docker 
                    docker compose -f docker-compose.yml up -d
                  command_timeout: 25m