name: Deploy Templates
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: 🚀 Deploy Comments Templates
    runs-on: ubuntu-latest

    steps:
    - name: 🚚 Get Latest Code
      uses: actions/checkout@v3

    - name: 📂 Sync Production Config
      uses: easingthemes/ssh-deploy@v4.0.5
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        SOURCE: config.production.json
        TARGET: /var/path.../
        ARGS: -rlgoDzvc -i -og --chown=user:user

    - name: 📂 Sync Comments Email Templates
      uses: easingthemes/ssh-deploy@v4.0.5
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        SOURCE: email-templates/comments/
        TARGET: /var/path.../
        ARGS: -rlgoDzvc -i -og --chown=user:user